export const normalKeyboard = [
    {value:'CE',type:'operator clear',},
    {value:'%',type:'operator percent',},
    {value:'DEL',type:'operator delete',},
    {value:'÷',type:'math-operator divide',},
    {value:'7',type:'number',},
    {value:'8',type:'number',},
    {value:'9',type:'number',},
    {value:'×',type:'math-operator multiply',},
    {value:'4',type:'number',},
    {value:'5',type:'number',},
    {value:'6',type:'number',},
    {value:'-',type:'math-operator minus',},
    {value:'1',type:'number',},
    {value:'2',type:'number',},
    {value:'3',type:'number',},
    {value:'+',type:'math-operator add',},
    {value:'±',type:'operator toggle',},
    {value:'0',type:'number',},
    {value:'.',type:'number dot',},
    {value:'=',type:'math-operator equal',}
];
export const scienceKeyboard = [
  {value:'x^2',},
  {value:'x^y',},
  {value:'sin',},
  {value:'cos',},
  {value:'tan',},
  {value:'√',},
  {value:'10^x',},
  {value:'log',},
  {value:'Exp',},
  {value:'Mod',},
  {value:'CE',},
  {value:'DEL',},
  {value:'÷',},
  {value:'π',},

];
